### ISSUE TITLE
can we create topic with one partition using this library for kafka 0.10.0.1

### ISSUE THREAD

**Issue by chandradeepak** [wvanbergen/kazoo-go#29]
I am using kafka 0.10.0.1 . can i create topic. My default no of partitions is 5. can i customize and create 1 partition topic using this library. also note that the kafka version is latest and it doesnt use zoo keeper for storing the meta data. Does this still support kafka  latest version.

**Comment by chandradeepak** [comment]
i tried creating it in kafka  0.10.0.1 by using the pull request submitted. it worked. so when is the pull request going to be merged ?

**Comment by F21** [comment]
Hey @chandradeepak PR #25 was merge, so let's close this issue.

**Comment by chandradeepak** [comment]
makes sense thanks for merging it .
